services:
  delay-server:
    build: ./delay-server
    networks:
      mail-1_net:
        ipv4_address: 172.21.0.2
      mail-2_net:
        ipv4_address: 172.22.0.2
    cap_add:
      - NET_ADMIN
    privileged: true

  mail-1:
    build: ./mail-server
    hostname: mail-1
    environment:
      - HOSTNAME=mail-1
      - DOMAIN=a.com
      - GATEWAY=172.21.0.2
    networks:
      mail-1_net:
        ipv4_address: 172.21.0.3
    cap_add:
      - NET_ADMIN

  mail-2:
    build: ./mail-server
    hostname: mail-2
    environment:
      - HOSTNAME=mail-2
      - DOMAIN=a.com
      - GATEWAY=172.22.0.2
    networks:
      mail-2_net:
        ipv4_address: 172.22.0.3
    cap_add:
      - NET_ADMIN

  edge-proxy:
    build: ./edge-proxy
    environment:
      - MAIL_1=172.21.0.3
      - MAIL_2=172.22.0.3
      - DELAY_1=172.21.0.2
      - DELAY_2=172.22.0.2
    networks:
      mail-1_net:
        ipv4_address: 172.21.0.4
      mail-2_net:
        ipv4_address: 172.22.0.4
    cap_add:
      - NET_ADMIN
    ports:
      - "10025:10025"
      - "10143:10143"
      - "20025:20025"
      - "20143:20143"

networks:
  mail-1_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

  mail-2_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24